services:
    _defaults:
        autowire: true
        autoconfigure: true

    Ecosystem\BusConsumerBundle\Command\:
        resource: '../src/Command'

    Ecosystem\BusConsumerBundle\Service\:
        resource: '../src/Service'
