services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        Ecosystem\BusConsumerBundle\Handler\HandlerInterface:
            tags: ['ecosystem.bus.handler']

    Ecosystem\BusConsumerBundle\Command\:
        resource: '../src/Command'

    Ecosystem\BusConsumerBundle\Service\:
        resource: '../src/Service'
